version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: citizen-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - citizen-net

  backend:
    build:
      context: ../citizen-portal-backend
    image: citizen-portal-backend:prod
    container_name: citizen-backend
    ports:
      - "5000:5000"
    env_file:
      - ../citizen-portal-backend/.env.docker
    depends_on:
      - mongodb
    networks:
      - citizen-net

  frontend:
    build:
      context: ../citizen-portal-frontend
    image: citizen-portal-frontend:prod
    container_name: citizen-frontend
    ports:
      - "5173:80"
    env_file:
      - ../citizen-portal-frontend/.env.docker
    depends_on:
      - backend
    networks:
      - citizen-net

volumes:
  mongodb_data:
    external: true

networks:
  citizen-net:
    driver: bridge
